language: php

services:
  - docker

before_install:
  - docker build -t flyimg .
  - docker run -t -d -i -v $(pwd):/var/www/html --name flyimg flyimg
  - docker exec -it flyimg sh -c "composer install"

script:
  - docker exec -it flyimg sh -c "vendor/bin/phpunit"

notifications:
  email:
    - sadoknet@gmail.com
