language: php

services:
  - docker

before_install:
  - docker build -t flyimg .
  - docker run -t -d -i -v $(pwd):/var/www/html --name flyimg flyimg
  - docker exec flyimg composer install

script:
  - docker exec flyimg phpunit

notifications:
  email:
    - sadoknet@gmail.com
