application_name: Flyimg.io

#debug
debug: false

#path to mozjpeg bin
mozjpeg_path: /opt/mozjpeg/bin/cjpeg

#By default cahing is enabled and it use Redis for aching meta-data
cache: true

#options separator
options_separator: ,

#restrict domains, false by default
restricted_domains: false

#if restricted_domains is enabled, put whitelist domains here
whitelist_domains:
    - www.mozilla.org

#Default storage system is local, to use use AWS S3, change this param to s3
storage_system: local

#In case storage_system: s3, you need to add those AWS S3 parameters:
aws_s3:
  access_id: ""
  secret_key: ""
  region: ""
  bucket_name: ""

#Keys used in url to match options. Ex: q_80,w_200,h_100
options_keys:
  moz: mozjpeg
  q: quality
  unsh: unsharp
  w: width
  h: height
  c: crop
  bg: background
  st: strip
  rz: resize
  g: gravity
  f: filter
  sc: scale
  sf: sampling-factor
  rf: refresh
  ett: extent
  par: preserve-aspect-ratio
  pns: preserve-natural-size


#Default options values
default_options:
  mozjpeg: 1
  quality: 90
  unsharp: null
  width: null
  height: null
  crop: null
  background: null
  strip: 1
  resize: null
  gravity: Center
  filter: Lanczos
  scale: null
  sampling-factor: 1x1
  refresh: false
  extent: null
  preserve-aspect-ratio: 1
  preserve-natural-size: 1
  # private options set here
  thread: 1
