name: CD
on:
  push:
    branches:
      - main
jobs:
  create_tag:
    name: Create new Tag and Release
    runs-on: ubuntu-18.04
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Generate CHANGELOG
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        id: change_log
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          release_branches: main

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.change_log.outputs.changelog }}

  docker_publish:
    name: Docker Build and Push
    runs-on: ubuntu-18.04
    needs: create_tag
    outputs:
      new_tag: ${{ needs.create_tag.outputs.new_tag }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            flyimg/flyimg-build:latest
            flyimg/flyimg-build:${{ needs.create_tag.outputs.new_tag }}

  deploy_demo:
    name: Deploy to Demo oi.flyimg.io
    runs-on: ubuntu-18.04
    needs: docker_publish
    steps:
      - name: Deploy new version of Flyimg to the demo server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FLYIMG_DEMO_HOST }}
          username: ${{ secrets.FLYIMG_DEMO_USERNAME }}
          key: ${{ secrets.FLYIMG_DEMO_KEY }}
          script: |
            bash -c "docker rm -f flyimg &>/dev/null"
            docker run -itd -p 8080:80 --name flyimg flyimg/flyimg-build:${{ needs.docker_publish.outputs.new_tag }}
